### ISSUE TITLE
Any demo of this

### ISSUE THREAD

**Issue by tyeeman** [intothevoid/likho#6]
Features look good. Any demo anywhere? I see your site uses Hugo. Are you going to change to Likho?

**Comment by intothevoid** [comment]
Hi @tyeeman, I don't have a demo yet but I should have one in a week or two. My plan is to move from Hugo to Likho to simplify things and have a simple markdown -> html workflow. Hugo is very extensive I am trying to build something simple and fast. I've attached an image to show you what the generated site looks like at the moment. 

![blog_ss](https://github.com/user-attachments/assets/e6ab5ab9-dd52-4259-89b1-4efbedb3d68a)

**Comment by tyeeman** [comment]
Thanks! Will this build on Windows? Sometimes there is the backslash/forwardslash path problem but sometimes not.

**Comment by tyeeman** [comment]
OK, Update - It works on Windows! It built fine and runs good, but when building, I see all output that is being written to all the posts/pages in my cmd window. That's not necessary is it? Just slows the process if there are lots of posts/pages.

Also, tags are not showing. Personally they are very important to me but maybe you haven't written the code yet for tags??

This is the output I see in my cmd window for tags - 
```
2024/09/30 19:22:54 Data being passed to template: {Posts:[{Title:my-test-post Description:description Date:2024-09-12 00:00:00 +0000 UTC Tags:[post post2] Content:
```

Question - are tags supposed to be clickable to take us to a page with all posts with that clicked tag?

**Comment by intothevoid** [comment]
Hey thanks for testing it out and glad it works for you on Windows. The output are just logs I will disable them in the next couple of updates. Tags and some features like RSS generation are still a work in progress. I plan on implementing them soon. The code to process them is present they just need to be hooked up.

**Comment by tyeeman** [comment]
Great, looking forward to it.

**Comment by intothevoid** [comment]
Improved the logging, and added tagging support. Clicking tags should take you to a page which lists all posts with that tag. Let me know how it goes for you and thanks again for helping me test this!

**Comment by tyeeman** [comment]
Thanks for the update. I still don't see any tags though.

Small fyi - the generated Windows executable does not have a .exe extension. 

Update - Yes, I can see tags now. I forgot to copy the tags template to my site folder. Is there a simple way to show each posts tags also on the main listing page just under the post title?

**Comment by intothevoid** [comment]
The following should give you the extension if building on the command line -

```bash
go build -o likho.exe ./cmd/likho
```

If I show tags on the main (landing) page it will clutter up the UI. You can however customise the look and feel by tweaking the index.html template to add elements or main.css to adjust styling. I plan to eventually support themes but I want to get all the basics working first. 

If you end up using likho for your blog please leave a link / star the repo, I'll be happy to link to it as a showcase. Cheers

**Comment by intothevoid** [comment]
Closing this issue - working tags are now available in the main branch
